import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";

export type PdfReportRow = {
  device_name: string;
  appliance_type: string;
  measured_kwh: number;
  estimated_kwh: number | null;
  average_watts: number;
  variable_cost_php: number;
  limit_php: number | null;
  budget_percent: number | null;
};

type ReportPdfInput = {
  accountEmail: string;
  period: "daily" | "weekly" | "monthly";
  start: Date;
  end: Date;
  rows: PdfReportRow[];
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 44;
const GREEN = rgb(0.06, 0.72, 0.4);
const INK = rgb(0.08, 0.11, 0.13);
const MUTED = rgb(0.38, 0.42, 0.45);
const LINE = rgb(0.86, 0.88, 0.89);

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(date);
}

function formatNumber(value: number, digits = 2): string {
  return new Intl.NumberFormat("en-PH", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  }).format(value);
}

function truncate(text: string, font: PDFFont, size: number, maxWidth: number): string {
  if (font.widthOfTextAtSize(text, size) <= maxWidth) return text;
  let result = text;
  while (result.length > 1 && font.widthOfTextAtSize(`${result}...`, size) > maxWidth) {
    result = result.slice(0, -1);
  }
  return `${result}...`;
}

function drawHeader(page: PDFPage, bold: PDFFont, regular: PDFFont, input: ReportPdfInput): number {
  page.drawText("WattWise", { x: MARGIN, y: PAGE_HEIGHT - MARGIN, size: 14, font: bold, color: GREEN });
  page.drawText(`${input.period[0].toUpperCase()}${input.period.slice(1)} Energy Report`, {
    x: MARGIN,
    y: PAGE_HEIGHT - MARGIN - 34,
    size: 22,
    font: bold,
    color: INK,
  });
  page.drawText(`${formatDate(input.start)} to ${formatDate(input.end)}  |  Asia/Manila`, {
    x: MARGIN,
    y: PAGE_HEIGHT - MARGIN - 56,
    size: 9,
    font: regular,
    color: MUTED,
  });
  page.drawText(`Account: ${input.accountEmail}`, {
    x: MARGIN,
    y: PAGE_HEIGHT - MARGIN - 71,
    size: 9,
    font: regular,
    color: MUTED,
  });
  return PAGE_HEIGHT - MARGIN - 104;
}

function drawTableHeader(page: PDFPage, bold: PDFFont, y: number): number {
  page.drawRectangle({ x: MARGIN, y: y - 17, width: PAGE_WIDTH - MARGIN * 2, height: 28, color: rgb(0.95, 0.97, 0.96) });
  const labels = [
    ["Appliance", MARGIN + 8],
    ["Actual", 250],
    ["Estimated", 312],
    ["Avg W", 382],
    ["Cost PHP", 430],
    ["Limit used", 495],
  ] as const;
  labels.forEach(([label, x]) => page.drawText(label, { x, y: y - 6, size: 8, font: bold, color: MUTED }));
  return y - 34;
}

function drawFooter(page: PDFPage, regular: PDFFont, pageNumber: number): void {
  page.drawText("Generated by WattWise. Variable energy cost excludes fixed monthly charges.", {
    x: MARGIN,
    y: 24,
    size: 7.5,
    font: regular,
    color: MUTED,
  });
  page.drawText(`Page ${pageNumber}`, {
    x: PAGE_WIDTH - MARGIN - 34,
    y: 24,
    size: 7.5,
    font: regular,
    color: MUTED,
  });
}

export async function buildReportPdf(input: ReportPdfInput): Promise<Uint8Array> {
  const document = await PDFDocument.create();
  const regular = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);
  let pageNumber = 1;
  let page = document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = drawHeader(page, bold, regular, input);

  const totalKwh = input.rows.reduce((sum, row) => sum + row.measured_kwh, 0);
  const totalCost = input.rows.reduce((sum, row) => sum + row.variable_cost_php, 0);
  page.drawText("SUMMARY", { x: MARGIN, y, size: 8, font: bold, color: MUTED });
  page.drawText(`${formatNumber(totalKwh, 4)} kWh`, { x: MARGIN, y: y - 25, size: 18, font: bold, color: INK });
  page.drawText("Measured usage", { x: MARGIN, y: y - 40, size: 8, font: regular, color: MUTED });
  page.drawText(`PHP ${formatNumber(totalCost)}`, { x: 220, y: y - 25, size: 18, font: bold, color: INK });
  page.drawText("Variable energy cost", { x: 220, y: y - 40, size: 8, font: regular, color: MUTED });
  page.drawText(String(input.rows.length), { x: 420, y: y - 25, size: 18, font: bold, color: INK });
  page.drawText("Appliances", { x: 420, y: y - 40, size: 8, font: regular, color: MUTED });

  y = drawTableHeader(page, bold, y - 78);
  if (input.rows.length === 0) {
    page.drawText("No registered appliances or telemetry were found for this period.", {
      x: MARGIN + 8,
      y,
      size: 10,
      font: regular,
      color: MUTED,
    });
  }

  for (const row of input.rows) {
    if (y < 72) {
      drawFooter(page, regular, pageNumber);
      pageNumber += 1;
      page = document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = drawTableHeader(page, bold, PAGE_HEIGHT - MARGIN);
    }

    page.drawText(truncate(row.device_name, bold, 9, 152), { x: MARGIN + 8, y, size: 9, font: bold, color: INK });
    page.drawText(truncate(row.appliance_type, regular, 7.5, 152), { x: MARGIN + 8, y: y - 13, size: 7.5, font: regular, color: MUTED });
    page.drawText(formatNumber(row.measured_kwh, 4), { x: 250, y, size: 8.5, font: regular, color: INK });
    page.drawText(row.estimated_kwh === null ? "-" : formatNumber(row.estimated_kwh, 4), { x: 312, y, size: 8.5, font: regular, color: INK });
    page.drawText(formatNumber(row.average_watts, 1), { x: 382, y, size: 8.5, font: regular, color: INK });
    page.drawText(formatNumber(row.variable_cost_php), { x: 430, y, size: 8.5, font: regular, color: INK });
    page.drawText(row.budget_percent === null ? "-" : `${formatNumber(row.budget_percent, 1)}%`, { x: 495, y, size: 8.5, font: regular, color: INK });
    page.drawLine({ start: { x: MARGIN, y: y - 23 }, end: { x: PAGE_WIDTH - MARGIN, y: y - 23 }, thickness: 0.6, color: LINE });
    y -= 42;
  }

  drawFooter(page, regular, pageNumber);
  document.setTitle(`WattWise ${input.period} energy report`);
  document.setAuthor("WattWise");
  document.setSubject("Household appliance energy usage and cost report");
  document.setCreationDate(new Date());
  return document.save();
}
