"use client";
import { useState } from "react";

type User = { id: string; email: string; full_name: string | null; role: string; manager_id: string | null; disabled_at: string | null; must_update_password: boolean };

export default function AdminUsersTable({ users, managers }: { users: User[]; managers: User[] }) {
  const [rows, setRows] = useState(users); const [editing, setEditing] = useState<User | null>(null); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false);
  async function save() { if (!editing) return; setSaving(true); const res = await fetch(`/api/admin/users/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role: editing.role, manager_id: editing.manager_id || null, must_update_password: editing.must_update_password, disabled: Boolean(editing.disabled_at), reason }) }); const json = await res.json(); setSaving(false); if (!res.ok) { alert(json.error || "Unable to save user"); return; } setRows(rows.map((row) => row.id === editing.id ? json.data : row)); setEditing(null); setReason(""); }
  function openEdit(user: User) { setEditing({ ...user }); setReason(""); }
  return <>
    <div className="overflow-x-auto rounded-lg border border-white/10 bg-surface"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-white/50"><tr>{["Name","Email","Role","Manager","Status","Created","Actions"].map((h)=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{rows.map((u)=><tr key={u.id} className="border-b border-white/5"><td className="p-4">{u.full_name||"—"}</td><td className="p-4">{u.email}</td><td className="p-4">{u.role}</td><td className="max-w-32 truncate p-4 text-xs">{managers.find((m)=>m.id===u.manager_id)?.full_name || u.manager_id || "—"}</td><td className="p-4"><span className={u.disabled_at?"text-danger":"text-mint"}>{u.disabled_at?"Disabled":"Active"}</span></td><td className="p-4 text-white/50">{new Date((u as User & {created_at:string}).created_at).toLocaleDateString()}</td><td className="p-4"><button onClick={()=>openEdit(u)} className="rounded-md border border-mint/30 px-3 py-1.5 text-xs font-semibold text-mint hover:bg-mint/10">Configure</button></td></tr>)}</tbody></table></div>
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-xl border border-white/10 bg-surface p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Configure user</h2><p className="text-sm text-white/50">{editing.email}</p></div><button onClick={()=>setEditing(null)} className="text-white/50 hover:text-white">✕</button></div><div className="space-y-4"><label className="block text-sm">Role<select value={editing.role} onChange={(e)=>setEditing({...editing,role:e.target.value})} className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2"><option value="user">User</option><option value="manager">Manager</option><option value="tenant">Tenant</option><option value="super_admin">Super admin</option></select></label><label className="block text-sm">Manager<select value={editing.manager_id||""} onChange={(e)=>setEditing({...editing,manager_id:e.target.value||null})} className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2"><option value="">No manager</option>{managers.filter((m)=>m.id!==editing.id).map((m)=><option key={m.id} value={m.id}>{m.full_name||m.email}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.must_update_password} onChange={(e)=>setEditing({...editing,must_update_password:e.target.checked})}/> Require password update on next login</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(editing.disabled_at)} onChange={(e)=>setEditing({...editing,disabled_at:e.target.checked?new Date().toISOString():null})}/> {editing.disabled_at?"Account disabled":"Disable account"}</label><label className="block text-sm">Reason<textarea value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Why is this change being made?" className="mt-1 min-h-20 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2"/></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setEditing(null)} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Cancel</button><button disabled={saving} onClick={save} className="rounded-lg bg-mint px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{saving?"Saving…":"Save changes"}</button></div></div></div>}
  </>;
}
